# Generated by Django 6.0.3 on 2026-04-03 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('site_id', models.IntegerField(max_length=11, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('ai_model', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
