# Generated by Django 6.0.3 on 2026-04-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('site_id', models.IntegerField(max_length=11, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'fire_detection',
                'managed': True,
            },
        ),
    ]
