# Generated by Django 3.2.20 on 2024-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helikite',
            fields=[
                ('serial_number', models.CharField(help_text='헬리카이트 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('cubic', models.IntegerField(blank=True, help_text='큐빅', null=True)),
                ('type', models.CharField(blank=True, help_text='형태', max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, help_text='무게', null=True)),
                ('payload', models.FloatField(blank=True, help_text='페이로드', null=True)),
                ('production_year', models.TextField(blank=True, help_text='제작 년도(1901-2155)', null=True)),
                ('image_file_path', models.CharField(blank=True, help_text='헬리카이트 이미지 파일 경로', max_length=100, null=True)),
            ],
            options={
                'db_table': 'helikite',
                'managed': False,
            },
        ),
    ]
