# Generated by Django 6.0.3 on 2026-04-06 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winch',
            fields=[
                ('serial_number', models.CharField(help_text='윈치 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('primary_sensor', models.CharField(blank=True, help_text='기본 센서', max_length=100, null=True)),
                ('extended_sensor', models.CharField(blank=True, help_text='확장 센서', max_length=100, null=True)),
                ('tetherline_length', models.FloatField(blank=True, help_text='티더선 전체 길이', null=True)),
                ('tetherline_limit_tension', models.FloatField(blank=True, help_text='티더선 한계 장력', null=True)),
                ('production_year', models.IntegerField(blank=True, help_text='제작 년도(1901-2155)', null=True)),
            ],
            options={
                'db_table': 'winch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WinchDataLog',
            fields=[
                ('winch_data_log_id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('tetherline_length', models.FloatField(blank=True, help_text='티더선 길이', null=True)),
                ('tetherline_angle', models.FloatField(blank=True, help_text='티더선 각도', null=True)),
                ('tetherline_tension', models.FloatField(blank=True, help_text='티더선 장력', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='기압', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='온도', null=True)),
                ('winch_serial_number', models.ForeignKey(blank=True, db_column='winch_serial_number', help_text='윈치 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winch.winch')),
            ],
            options={
                'db_table': 'winch_data_log',
                'managed': True,
            },
        ),
    ]
