# Generated by Django 3.2.20 on 2024-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraView',
            fields=[
                ('camera_view_id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('cardinal_direction', models.CharField(blank=True, help_text='방위', max_length=100, null=True)),
            ],
            options={
                'db_table': 'camera_view',
                'managed': False,
            },
        ),
    ]
