# Generated by Django 6.0.3 on 2026-04-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraView',
            fields=[
                ('camera_view_id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜', null=True)),
                ('latitude', models.CharField(blank=True, help_text='위도', max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, help_text='경도', max_length=100, null=True)),
                ('cardinal_direction', models.CharField(blank=True, help_text='방위', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Camera view',
                'verbose_name_plural': 'Camera view',
                'db_table': 'camera_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('serial_number', models.CharField(help_text='카메라 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('availability', models.CharField(blank=True, choices=[('고장', '고장'), ('파손', '파손'), ('기타', '기타'), ('분실', '분실')], help_text='가용 가능 여부', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, help_text='비고', max_length=100, null=True)),
                ('maximum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최대각', null=True)),
                ('minimum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최소각', null=True)),
                ('maximum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최대각', null=True)),
                ('minimum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최소각', null=True)),
                ('maximum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최대각', null=True)),
                ('minimum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최소각', null=True)),
                ('zoom_magnification', models.IntegerField(blank=True, help_text='Zoom 배율', null=True)),
                ('night_vision', models.IntegerField(blank=True, choices=[(None, '가능'), (1, '불가능')], help_text='나이트 비전 가능 여부', null=True)),
                ('protocol', models.IntegerField(blank=True, help_text='프로토콜 타입', null=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Camera',
                'db_table': 'camera',
                'managed': True,
            },
        ),
    ]
