# Generated by Django 4.2a1 on 2023-02-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logger', '0002_auto_20190109_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
    ]
