"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from django_eventstream.utils import have_channels
from .jazzmin import JAZZMIN_SETTINGS
from .database import DATABASE_SETTINGS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# with open('/etc/secret_key.txt') as f:
with open('./secret_key.txt') as f:
    SECRET_KEY = f.read().strip()  # 패스워드를 암호화할 때 사용하는 키
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # 웹에서 오류가 났을 때 자세한 내용을 알려준다. 배포때는 false로 해야 한다
DATETIME_FORMAT = "Y-m-d H:i:s"

# APPEND_SLASH = False

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8001', 'http://192.168.88.20:8001', 'http://skyeyeserver.duckdns.org:8001']

# Application definition
AUTH_USER_MODEL = 'accounts.User'
# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.AllowAllUsersModelBackend',
#     'accounts.backends.CaseInsensitiveModelBackend',
# )

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

if have_channels():
    INSTALLED_APPS.append('channels')  # pip install channels

INSTALLED_APPS.extend([
    # local app
    'sse',
    'accounts',
    'camera',
    'fire_detection',
    'helikite',
    'mission_device',
    'notification',
    'skyeye',
    'winch',
    # 3rd party app
    'rangefilter',  # pip install django-admin-rangefilter
    'debug_toolbar',  # pip install django-debug-toolbar
    'django_db_logger',  # pip install django-db-logger
    'drf_yasg',  # pip install drf_yasg
    'rest_framework',  # pip install djangorestframework
    'rest_framework.authtoken',
    'django_eventstream',  # pip install django-eventstream
    # 'drf_api_logger',  # pip install drf-api-logger
    # 'bootstrap4',  # pip install django-bootstrap4
])

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
SCHEDULER_DEFAULT = True

MIDDLEWARE = [
    'django_grip.GripMiddleware',  # add
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # add
    # 'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',  # add
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

INTERNAL_IPS = ['127.0.0.1']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # 인증된 요청에 대해서만 view 호출
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',  # 비인증 요청에 대해서는 읽기만 허용
    ]
}

# email 알림 전송 설정
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '118.128.208.148'
EMAIL_USE_TLS = False
EMAIL_PORT = 25
EMAIL_HOST_USER = 'jhyang@skysys.co.kr'
EMAIL_HOST_PASSWORD = 'tmzkdl1!'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ROOT_URLCONF = "server.urls"

# 템플릿 설정
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# DRF_API_LOGGER_DATABASE = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'db': {
            'handlers': ['db_log'],
            'level': 'DEBUG'
        },
        'django.request': {  # logging 500 errors to database
            'handlers': ['db_log'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}

WSGI_APPLICATION = "server.wsgi.application"
ASGI_APPLICATION = "server.asgi.application"

SESSION_COOKIE_AGE = 3600  # 초 단위로 세션 타임아웃 시간을 설정
SESSION_SAVE_EVERY_REQUEST = True  # 사용자가 리퀘스트를 서버로 날릴 때마다 서버의 세션 정보와 클라이언트의 세션 정보를 갱신할 것인지를 설정

EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.DjangoModelStorage'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = DATABASE_SETTINGS

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization(지역시각 및 다국어 설정)
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# 주의할 점. STATIC_ROOT 경로는 STATICFILES_DIRS 등록된 경로와 같은 경로가 있어서는 안 됩니다. 남들이 잘 안 쓸만한 이상한 이름(staticfiles?)을 쓰세요.
# https://blog.hannal.com/2015/04/start_with_django_webframework_06/
# => (staticfiles.E002) The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# collectstatic 경로 / Debug = True 일때 작동안함
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_SETTING = JAZZMIN_SETTINGS