# Generated by Django 6.0.3 on 2026-04-06 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missiondevice',
            fields=[
                ('serial_number', models.CharField(help_text='임무 장치 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('availability', models.CharField(blank=True, choices=[('고장', '고장'), ('파손', '파손'), ('기타', '기타'), ('분실', '분실')], help_text='가용 가능 여부', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, help_text='비고', max_length=100, null=True)),
                ('camera_serial_number', models.OneToOneField(blank=True, db_column='camera_serial_number', help_text='카메라 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='camera.camera')),
            ],
            options={
                'db_table': 'missiondevice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MissiondeviceDataLog',
            fields=[
                ('missiondevice_data_log_id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('roll', models.FloatField(blank=True, help_text=' Roll', null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Pitch', null=True)),
                ('yaw', models.FloatField(blank=True, help_text='Yaw', null=True)),
                ('camera_roll', models.FloatField(blank=True, help_text='카메라 Roll', null=True)),
                ('camera_pitch', models.FloatField(blank=True, help_text='카메라 Pitch', null=True)),
                ('camera_yaw', models.FloatField(blank=True, help_text='카메라 Yaw', null=True)),
                ('camera_zoom', models.IntegerField(blank=True, help_text='카메라 Zoom', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='기압', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude2', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude3', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude4', models.FloatField(blank=True, help_text='고도', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='온도', null=True)),
                ('missiondevice_serial_number', models.ForeignKey(blank=True, db_column='missiondevice_serial_number', help_text='임무 장치 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission_device.missiondevice')),
            ],
            options={
                'db_table': 'missiondevice_data_log',
                'managed': True,
                'indexes': [models.Index(fields=['date'], name='missiondevi_date_7197f8_idx')],
            },
        ),
    ]
