# Generated by Django 3.2.20 on 2024-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('serial_number', models.CharField(help_text='카메라 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('maximum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최대각', null=True)),
                ('minimum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최소각', null=True)),
                ('maximum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최대각', null=True)),
                ('minimum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최소각', null=True)),
                ('maximum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최대각', null=True)),
                ('minimum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최소각', null=True)),
                ('zoom_magnification', models.IntegerField(blank=True, help_text='무게', null=True)),
                ('night_vision', models.IntegerField(blank=True, help_text='나이트 비전 가능 여부', null=True)),
                ('protocol', models.IntegerField(blank=True, help_text='프로토콜 타입', null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Missiondevice',
            fields=[
                ('serial_number', models.CharField(help_text='임무 장치 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('primary_sensor', models.CharField(blank=True, help_text='기본 센서', max_length=100, null=True)),
                ('extended_sensor', models.CharField(blank=True, help_text='확장 센서', max_length=100, null=True)),
                ('communication_type', models.CharField(blank=True, help_text='통신방식', max_length=100, null=True)),
                ('mobile_service_company', models.CharField(blank=True, help_text='통신사', max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, help_text='무게', null=True)),
                ('production_year', models.TextField(blank=True, help_text='제작 년도(1901-2155)', null=True)),
            ],
            options={
                'db_table': 'missiondevice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissiondeviceDataLog',
            fields=[
                ('missiondevice_data_log_id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('roll', models.FloatField(blank=True, help_text=' Roll', null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Pitch', null=True)),
                ('yaw', models.FloatField(blank=True, help_text='Yaw', null=True)),
                ('camera_roll', models.FloatField(blank=True, help_text='카메라 Roll', null=True)),
                ('camera_pitch', models.FloatField(blank=True, help_text='카메라 Pitch', null=True)),
                ('camera_yaw', models.FloatField(blank=True, help_text='카메라 Yaw', null=True)),
                ('camera_zoom', models.IntegerField(blank=True, help_text='카메라 Zoom', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='기압', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude2', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude3', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude4', models.FloatField(blank=True, help_text='고도', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='온도', null=True)),
                ('voltage', models.FloatField(blank=True, help_text='전압', null=True)),
                ('rssi', models.IntegerField(blank=True, db_column='rssi_lte', help_text='무선통신 수신 감도', null=True)),
            ],
            options={
                'db_table': 'missiondevice_data_log',
                'managed': False,
            },
        ),
    ]
