# Generated by Django 6.0.3 on 2026-04-03 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('serial_number', models.CharField(help_text='카메라 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('availability', models.CharField(blank=True, choices=[('고장', '고장'), ('파손', '파손'), ('기타', '기타'), ('분실', '분실')], help_text='가용 가능 여부', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, help_text='비고', max_length=100, null=True)),
                ('maximum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최대각', null=True)),
                ('minimum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최소각', null=True)),
                ('maximum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최대각', null=True)),
                ('minimum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최소각', null=True)),
                ('maximum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최대각', null=True)),
                ('minimum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최소각', null=True)),
                ('zoom_magnification', models.IntegerField(blank=True, help_text='무게', null=True)),
                ('night_vision', models.IntegerField(blank=True, choices=[(None, '가능'), (1, '불가능')], help_text='나이트 비전 가능 여부', null=True)),
                ('protocol', models.IntegerField(blank=True, help_text='프로토콜 타입', null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Missiondevice',
            fields=[
                ('serial_number', models.CharField(help_text='임무 장치 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('availability', models.CharField(blank=True, choices=[('고장', '고장'), ('파손', '파손'), ('기타', '기타'), ('분실', '분실')], help_text='가용 가능 여부', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, help_text='비고', max_length=100, null=True)),
                ('camera_serial_number', models.OneToOneField(blank=True, db_column='camera_serial_number', help_text='카메라 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission_device.camera')),
            ],
            options={
                'db_table': 'missiondevice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MissiondeviceDataLog',
            fields=[
                ('missiondevice_data_log_id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('roll', models.FloatField(blank=True, help_text=' Roll', null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Pitch', null=True)),
                ('yaw', models.FloatField(blank=True, help_text='Yaw', null=True)),
                ('camera_roll', models.FloatField(blank=True, help_text='카메라 Roll', null=True)),
                ('camera_pitch', models.FloatField(blank=True, help_text='카메라 Pitch', null=True)),
                ('camera_yaw', models.FloatField(blank=True, help_text='카메라 Yaw', null=True)),
                ('camera_zoom', models.IntegerField(blank=True, help_text='카메라 Zoom', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='기압', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude2', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude3', models.FloatField(blank=True, help_text='고도', null=True)),
                ('altitude4', models.FloatField(blank=True, help_text='고도', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='온도', null=True)),
                ('voltage', models.FloatField(blank=True, help_text='전압', null=True)),
                ('rssi', models.IntegerField(blank=True, db_column='rssi_lte', help_text='무선통신 수신 감도', null=True)),
                ('missiondevice_serial_number', models.ForeignKey(blank=True, db_column='missiondevice_serial_number', help_text='임무 장치 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission_device.missiondevice')),
            ],
            options={
                'db_table': 'missiondevice_data_log',
                'managed': True,
                'indexes': [models.Index(fields=['date'], name='missiondevi_date_7197f8_idx')],
            },
        ),
    ]
