# Generated by Django 6.0.3 on 2026-04-06 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission_device', '0001_initial'),
        ('winch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(help_text='auto increment PK', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='장소명', max_length=100, null=True, unique=True)),
                ('installation_date', models.DateField(blank=True, help_text='설치 날짜', null=True)),
                ('gcs_serial_number', models.CharField(blank=True, help_text='gcs', max_length=100, null=True, unique=True)),
                ('video_stream_url', models.CharField(blank=True, help_text='비디오 스트림 URL', max_length=200, null=True)),
                ('missiondevice_pressure_offset', models.FloatField(default=0, help_text='임무장비 기압 오프셋')),
                ('winch_pressure_offset', models.FloatField(default=0, help_text='윈치 기압 오프셋')),
                ('missiondevice_altitude_low', models.FloatField(blank=True, help_text='임무장치 고도 하한', null=True)),
                ('winch_tetherline_angle_high', models.FloatField(blank=True, help_text='윈치 티더선 각도 상한', null=True)),
                ('winch_tetherline_angle_low', models.FloatField(blank=True, help_text='윈치 티더선 각도 하한', null=True)),
                ('alarm', models.SmallIntegerField(default=0, help_text='위험 상황 알림 여부')),
                ('state', models.SmallIntegerField(default=0, help_text='데이터 수신 상태')),
                ('missiondevice_serial_number', models.OneToOneField(blank=True, db_column='missiondevice_serial_number', help_text='설치된 임무장비 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission_device.missiondevice')),
                ('winch_serial_number', models.OneToOneField(blank=True, db_column='winch_serial_number', help_text='설치된 윈치 일련번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winch.winch')),
            ],
            options={
                'db_table': 'site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scan360Config',
            fields=[
                ('id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False)),
                ('step_angle', models.FloatField(blank=True, help_text='회전 각도', null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Pitch', null=True)),
                ('zoom_level', models.IntegerField(blank=True, help_text='줌레벨', null=True)),
                ('dwell_seconds', models.IntegerField(default=20, help_text='체류 시간(초)')),
                ('site', models.OneToOneField(db_column='site_id', help_text='사이트 번호', on_delete=django.db.models.deletion.CASCADE, related_name='scan360', to='skyeye.site')),
            ],
            options={
                'db_table': 'scan360_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(help_text='auto increment PK', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, help_text='날짜')),
                ('name', models.CharField(blank=True, help_text='지점명', max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='고도', null=True)),
                ('zoom_level', models.IntegerField(blank=True, help_text='줌레벨', null=True)),
                ('dwell_seconds', models.IntegerField(default=20, help_text='체류 시간(초)')),
                ('pitch', models.FloatField(blank=True, help_text='Pitch', null=True)),
                ('order', models.IntegerField(blank=True, help_text='순서', null=True)),
                ('site', models.ForeignKey(db_column='site_id', help_text='사이트 번호', on_delete=django.db.models.deletion.CASCADE, to='skyeye.site')),
            ],
            options={
                'db_table': 'poi',
                'managed': True,
            },
        ),
    ]
