# Generated by Django 3.2.20 on 2024-09-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('date', models.DateTimeField(auto_now=True, help_text='기본키', primary_key=True, serialize=False)),
                ('poi_id', models.IntegerField(help_text='지점 번호')),
                ('latitude', models.FloatField(blank=True, help_text='위도', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='고도', null=True)),
                ('zoom_level', models.IntegerField(blank=True, help_text='줌레벨', null=True)),
            ],
            options={
                'db_table': 'poi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(help_text='auto increment PK', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='장소명', max_length=100, null=True, unique=True)),
                ('installation_date', models.DateField(blank=True, help_text='설치 날짜', null=True)),
                ('gcs_serial_number', models.CharField(blank=True, help_text='gcs', max_length=100, null=True, unique=True)),
                ('missiondevice_pressure_offset', models.FloatField(default=0, help_text='임무장비 기압 오프셋')),
                ('winch_pressure_offset', models.FloatField(default=0, help_text='윈치 기압 오프셋')),
                ('missiondevice_altitude_low', models.FloatField(blank=True, help_text='임무장치 고도 하한', null=True)),
                ('winch_tetherline_angle_high', models.FloatField(blank=True, help_text='윈치 티더선 각도 상한', null=True)),
                ('winch_tetherline_angle_low', models.FloatField(blank=True, help_text='윈치 티더선 각도 하한', null=True)),
                ('alarm', models.SmallIntegerField(default=0, help_text='위험 상황 알림 여부')),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
    ]
