# Generated by Django 3.2.17 on 2026-04-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyeye', '0002_db_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='gcs_serial_number',
        ),
    ]
