# Generated by Django 3.2.17 on 2026-04-20 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyeye', '0003_remove_site_gcs_serial_number'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='site_id',
            field=models.ForeignKey(db_column='site_id', help_text='임무장치 사이트 번호', on_delete=django.db.models.deletion.DO_NOTHING, to='skyeye.site'),
        ),
        migrations.CreateModel(
            name='FireUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default=0, max_length=11)),
                ('site_id', models.ForeignKey(db_column='site_id', help_text='임무장치 사이트 번호', on_delete=django.db.models.deletion.DO_NOTHING, to='skyeye.site')),
            ],
            options={
                'db_table': 'fire_user_notification',
                'managed': True,
            },
        ),
    ]
